version: "3.9"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    command: ["docker/entrypoint.sh"]
    expose:
      - 8000
    restart: always
    env_file:
      - .env
    volumes:
      - media_volume:/app/upload
      - static_volume:/app/static
    depends_on:
      - redis_shop
      - db_shop
    networks:
      - net

  redis_shop:
    image: redis
    command: --port 6379
    ports:
      - 6379:6379
    networks:
      - net

  db_shop:
    image: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - net

  celery_shop:
    build:
      context: .
    container_name: celery_app
    command: ["docker/celery.sh", "celery"] # запуск скрипта для запуска celery
    env_file:
      - .env
    depends_on:
      - redis_shop
    networks:
      - net

  flower_shop:
    build:
      context: .
    container_name: flower_app
    command: ["docker/celery.sh", "flower"]  # запуск скрипта для запуска flower
    env_file:
      - .env
    depends_on:
      - redis_shop
      - celery_shop
    ports:
      - 5555:5555
    networks:
      - net

  nginx_shop:
    container_name: shop-nginx
    build: ./nginx
    volumes:
      - log_nginx:/var/log/nginx
      - media_volume:/app/upload
      - static_volume:/app/static
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - net

volumes:
  postgres_volume:
  static_volume:
  media_volume:
  log_nginx:

networks:
  net:
    driver: bridge