version: "3.9"

services:
  app:
    build:
      dockerfile: ./Dockerfile
#    command: gunicorn online_shop.wsgi:application --bind 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000

    ports:
      - 8000:8000
    restart: always
    env_file:
      - .env
    volumes:
      - upload:/app/upload
    depends_on:
      - redis_shop
      - db_shop
    networks:
      - net

  redis_shop:
    image: redis
    command: --port 6379
    ports:
      - 6379:6379
    networks:
      - net

  db_shop:
    image: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - net

#  celery_shop:
#    build:
#      context: .
#    container_name: celery_app
#    command: ["/app/docker/celery.sh", "celery"] # запуск скрипта для запуска celery
#    depends_on:
#      - redis_shop
#    networks:
#      - net
#
#  flower_shop:
#    build:
#      context: .
#    container_name: flower_app
#    command: ["/app/docker/celery.sh", "flower"]  # запуск скрипта для запуска flower
#    depends_on:
#      - redis_shop
#      - celery_shop
#    ports:
#      - 5555:5555
#    networks:
#      - net

#  nginx_shop:
#    container_name: shop-nginx
#    build: ./nginx
#    volumes:
#      - ./var/log/nginx:/var/log/nginx
#      - ./static:/usr/share/nginx/html/static
#      - ./templates/frontend:/usr/share/nginx/html
##      - ./media:/usr/share/nginx/html/static/images
#    ports:
#      - 80:80
#    depends_on:
#      - app
#    networks:
#      - net

volumes:
  postgres_volume:
  upload:

networks:
  net:
    driver: bridge