# Generated by Django 5.1.2 on 2024-11-02 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0008_alter_review_rate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specification",
            options={
                "verbose_name": "Спецификация товара",
                "verbose_name_plural": "Спецификации товаров",
            },
        ),
    ]
