# Generated by Django 5.1.2 on 2024-11-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0011_rename_description_productimage_alt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="tags",
            field=models.ManyToManyField(related_name="category", to="shopapp.tag"),
        ),
    ]
