# Generated by Django 5.1.2 on 2024-11-09 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0012_category_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="subcategories",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="shopapp.category",
                verbose_name="subcategories",
            ),
        ),
    ]
