# Generated by Django 5.1.2 on 2024-11-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0013_category_subcategories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="category", to="shopapp.tag"
            ),
        ),
    ]
