# Generated by Django 5.1.2 on 2024-11-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0014_alter_category_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Наименование тэга"),
        ),
    ]
