# Generated by Django 5.1.2 on 2024-11-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0016_alter_category_options_alter_category_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="category",
                to="shopapp.tag",
                verbose_name="Тэг",
            ),
        ),
    ]
