# Generated by Django 5.1.2 on 2024-11-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0018_sales"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="dateFrom",
            field=models.DateTimeField(blank=True, verbose_name="Дата начала скидки"),
        ),
        migrations.AlterField(
            model_name="sales",
            name="dateTo",
            field=models.DateTimeField(
                blank=True, verbose_name="Дата окончания скидки"
            ),
        ),
    ]
