# Generated by Django 5.1.2 on 2024-12-01 06:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0019_alter_sales_datefrom_alter_sales_dateto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                default=0,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
                verbose_name="Цена",
            ),
        ),
    ]
