# Generated by Django 5.1.2 on 2024-12-02 16:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0020_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="salePrice",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Цена со скидкой",
            ),
        ),
    ]
