# Generated by Django 5.1.2 on 2024-12-02 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ("created_at",),
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
        migrations.AlterModelOptions(
            name="orderinfobasket",
            options={
                "verbose_name": "Содержание заказа",
                "verbose_name_plural": "Содержание заказа",
            },
        ),
    ]
